"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const user_controller_1 = require("../controllers/user.controller");
const auth_1 = require("../middleware/auth");
const router = (0, express_1.Router)();
router.post("/signup", user_controller_1.createUser);
router.post("/login", user_controller_1.loginUser);
router.get("/current", auth_1.authMiddleware, user_controller_1.getCurrentUser);
exports.default = router;
